[package]
name = "netflix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[[bin]]
name = "ft-group-similar-titles"
path = "src/group-similar-titles.rs"

